### ISSUE TITLE
Error: Cannot find module 'chalk'

### ISSUE THREAD

**Issue by mikwerdna** [JoinColony/colonyStarter#22]
## Description

Step 2 fails to unpack the `colony-starter-basic` package. Following exception is thrown.

```
module.js:557
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/.../.../.config/yarn/global/node_modules/@colony/colony-starter/index.js:3:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

## Steps to Reproduce

0. Meet prerequisites listed on [Getting Started](https://github.com/JoinColony/colonyStarter).
1. Execute step 1.
2. As part of step 2, run following command: 

```shell
colony-starter colony-starter-basic
```

## Environment

`macOS 10.13.6`
`node 9.5.0`
`yarn 1.9.4`

**Comment by ryanchristo** [comment]
@mikwerdna Not sure how this one slipped through testing and review. The `chalk` dependency must have been installed globally on our end.

It should be fixed now with the latest release. Try running `yarn upgrade @colony/colony-starter` and then running the command again. Let me know if that works.

**Comment by mikwerdna** [comment]
@ryanchristo Thank you.

I upgraded, ran the command, and got another throw for the `commander` module. So I created an issue and sent you a PR for it.
