### ISSUE TITLE
Error: `createTask` - expected Buffer

### ISSUE THREAD

**Issue by MichaelHirn** [JoinColony/colonyStarter#43]
## Description

`yarn start` and `yarn test` fail with the following error:

```
● Colony Starter Basic › account[0] createTask() works

    TypeError: Expected Buffer

      at Object.encode (../node_modules/base-x/index.js:29:41)
      at encode (../node_modules/@colony/colony-js-contract-client/src/modules/paramTypes.js:112:21)
      at fn (../node_modules/@colony/colony-js-contract-client/src/modules/paramTypes.js:151:10)
      at ../node_modules/@colony/colony-js-contract-client/src/modules/paramConversion.js:38:11
          at Array.map (<anonymous>)
      at map (../node_modules/@colony/colony-js-contract-client/src/modules/paramConversion.js:36:10)
      at GetTask.convertOutputValues (../node_modules/@colony/colony-js-contract-client/src/classes/ContractMethod.js:126:12)
      at GetTask.task [as convertOutputValues] (../node_modules/@colony/colony-js-client/src/ColonyClient/callers/GetTask.js:60:11)
      at GetTask.convertOutputValues (../node_modules/@colony/colony-js-contract-client/src/classes/ContractMethodCaller.js:59:31)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at step (../node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at ../node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

## Steps to Reproduce

Followed all the steps in [Getting Started](https://github.com/JoinColony/colonyStarter) and [colony-starter-basic](https://github.com/JoinColony/colonyStarter/tree/master/packages/colony-starter-basic) up until the last command of `yarn start`/`yarn test`.

**Comment by ryanchristo** [comment]
@MichaelHirn Thanks for posting. Looking into it now. Will follow up later today.

**Comment by ryanchristo** [comment]
Hey @MichaelHirn! Sorry for the delay. We had to make some updates to the colonyJS library and we did some updates to colonyStarter in the process but all should be working again!

If you create a fresh starter pack by running `colony-starter colony-starter-basic`, it will install the latest version with the fix. I just tested it on my machine so you should be good to go. I'm going to close this issue but feel free to reopen it if need be.
